name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Functions
        run: supabase functions deploy amadeus-city-search
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}objects. This is most likely because the user is typing the city name but not completing the selection by clicking on an item in the autocomplete dropdown.

The fix is to ensure the user completes the selection process. If the dropdown is not appearing, the user needs to debug the `amadeus-city-search` Supabase function.

## 4. Summary of Debugging Steps for Lovable

1.  **Confirm Validation:** Verify that `departureLocation` and `destinationLocation` are `null` when the button is disabled. Use the temporary debug block in `TripIntakeForm.tsx` (Section 3.A).
2.  **Verify Selection:** Ensure that after typing a city name, the user **clicks on a suggestion** from the dropdown.
3.  **Check API:** If the dropdown is not appearing, check the browser's **Network** tab for the `amadeus-city-search` API call to diagnose issues with the Supabase Edge Function or Amadeus API integration.

This report provides the necessary context and steps to debug the issue in your development environment.


